
#ifndef __DEFAULTSKINBMP__H__
#define __DEFAULTSKINBMP__H__ 

typedef enum
{
	CMBDEFTHUMB_DOWN, //0
	CMBDEFTHUMB_HOVER,//1
	CMBDEFTHUMB_NORMAL,//2
	DLGBTN_CLOSENOR,//3
	DLGBTN_CLOSEOVER,//4
	DLGBTN_MAXIMIZENOR,//5
	DLGBTN_MAXIMIZEOVER,//6
	DLGBTN_MINIMIZENOR,//7
	DLGBTN_MINIMIZEOVER,//8
	DLGBTN_RESTORENOR,//9
	DLGBTN_RESTOREOVER,//0
	DLGBTN_SETNOTOPNOR,//1
	DLGBTN_SETNOTOPOVER,//2
	DLGBTN_SETTOPNOR,//3
	DLGBTN_SETTOPOVER,//4
	DLGTOOLBARBK,//5
	POPWINBKCENTERBOTTOM,//6
	POPWINBKCENTERTOP,//7
	POPWINBKLEFT,//8
	POPWINBKLEFTBOTTOM,//9
	POPWINBKLEFTTOP,//0
	POPWINBKRIGHT,//1
	POPWINBKRIGHTBOTTOM,//2
	POPWINBKRIGHTTOP,//3
	CHECKBTN_TYPE1ON,//4
	CHECKBTN_TYPE1OFF,//5
	GENPIC_TYPE1UP,//6
	GENPIC_TYPE1DWON,//7
	GENERAL_OK1,//8
	GENERAL_NG1,//9
	GENERAL_OK2,
	GENERAL_NG2,
	GENERAL_SEARCH,
	GENERAL_HELP,
	GENERAL_GUIDE,
	GENERAL_SETTING,
	GENERAL_RBUTTONON,
	GENERAL_REFRESH1,
	GENERAL_SAVE,
	GENERAL_REDO,
	GENERAL_UNDO,
	GENERAL_COPY,
	GENERAL_CUT,
	GENERAL_PASTE,
	GENERAL_REFRESH2,
	GENERAL_FORBIDDEN,
	GENERAL_INFORMATION,
	GENERAL_QUESTION,
	GENERAL_WARNING1,
	GENERAL_WARNING2,
	GENERAL_CALENDAR,
	GENERAL_HEART1,
	GENERAL_HEART2,
	GENERAL_ARROWDOWN,
	GENERAL_ARROWLEFT,
	GENERAL_ARROWRIGHT,
	GENERAL_ARROWUP,
	GENERAL_ADD1,
	GENERAL_ADD2,
	GENERAL_REMOVE1,
	GENERAL_REMOVE2,
	GENERAL_NG3,
	GENERAL_NG4,
	GENERAL_OK3,
	GENERAL_OK4,
	GENERAL_MAX
}GENERAL_IMG;

void  ExportDefSkins() ;
TCHAR *GetDefaultPicture(int nIndex=0) ;


#endif